config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :line_items, inverse_of: :invoice,  dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :user

  accepts_nested_attributes_for :line_items, allow_destroy: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  # Use optional: `true` to add line_item to invoice before invoice object actually exists
  belongs_to :invoice, optional: true
  belongs_to :product
  # accepts_nested_attributes_for :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :products, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.line_items.build
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
    @invoice.line_items.build
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    # raise params.inspect
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:title, :amount, :tax_percentage, :total_amount, :user_id, line_items_attributes: [:product_id, :invoice_id, :quantity, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:search_query].blank?
      @products = Product.includes(:tags, :taggings).all.page params[:page]
    else
      q_array_with_percetage_signs = params[:search_query].split(",").map {|val| "%#{val}%" }
      @products = Product.where(id: Tagging.where(tag_id: Tag.where("name ILIKE ANY ( array[?] )", q_array_with_percetage_signs).pluck(:id)).pluck(:product_id).uniq).page params[:page]
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to edit_product_path(@product), notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, alert: 'Product was successfully destroyed.' }
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :search_query, tag_ids: [])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, "#", class: "add_fields" + " #{args[:class]}", data: {id: id, fields: fields.gsub("\n", "")} )
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> Created by <%= current_user.email %> on <%=  Date.today.strftime("%d-%m-%Y") %></h3>
    </div>
    <div class="panel-body">

      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


      <div class="form-inputs">
        <%= f.input :title, required: true, input_html: { required: true } %>
      </div>

      <table class="table table-hover table-bordered dynamic-add">
        <thead>
          <tr>
            <th></th>
            <th>Quantity</th>
            <th>Product</th>
            <th>Price Per Unit</th>
          </tr>
        </thead>

      <tbody class="fields">    
        <%= f.simple_fields_for(:line_items) do |li| %>
          <%= render 'line_item', f: li%>
        <% end %>
      </tbody>
    </table>
        <%= link_to_add_row("Add Item", f, :line_items, class: 'btn btn-danger') %>
        <div class="slight-top-margin">
          <%= f.input :amount, readonly: true, input_html: {id: "amount-without-tax" } %>
          <%= f.input :tax_percentage, readonly: true, input_html: {value: 15} %>
          <%= f.input :total_amount, readonly: true, input_html: {id: "amount-with-tax"} %>
          <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id}%>
        </div>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-lg btn-success" %>
      </div>
    </div>
  </div>
<% end %>

app/views/invoices/_line_item.html.erb
<tr class="info">
  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to "Delete", "#", class: "remove_record" %>
    </td>
  <td> <%= f.input :quantity, label: false, input_html: {class: "product-quantity", data: {prices: Product.all.order(:name).pluck(:id, :price).each_with_object({}) {|(k, v), h| h[k] = v}.to_json  } } %></td>
  <td><%= f.collection_select :product_id, Product.all.order(:name), :id, :name, options={include_blank: false}, html_options={class: "form-control product-listing", data: {prices: Product.all.order(:name).pluck(:id, :price).each_with_object({}) {|(k, v), h| h[k] = v}.to_json  }}%></td>
  <td class="product-price"></td>
</tr>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="slight-top-margin panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"> Invoices</h3>
  </div>
  <div class="panel-body">
    <table class='table table-hover table-bordered'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Amount</th>
          <th>Tax percentage</th>
          <th>Total amount</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.title %></td>
            <td><%= invoice.amount %></td>
            <td><%= invoice.tax_percentage %></td>
            <td><%= invoice.total_amount %></td>
            <td><%= invoice.user.email %></td>
            <td><%= link_to 'Show', invoice %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<br>

<%= link_to 'New Invoice', new_invoice_path, class: "btn btn-success btn-block" %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="slight-top-margin col-md-8 offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> Invoice Title: <%= @invoice.title %></h3>
    </div>
    <div class="panel-body">
      <p>
        <strong>Title:</strong>
        <%= @invoice.title %>
      </p>

      <p>
        <strong>Amount:</strong>
        <%= @invoice.amount %>
      </p>

      <p>
        <strong>Tax percentage:</strong>
        <%= @invoice.tax_percentage %>
      </p>

      <p>
        <strong>Total amount:</strong>
        <%= @invoice.total_amount %>
      </p>

      <p>
        <strong>Invoice Creator Email:</strong>
        <%= @invoice.user.email %>
      </p>
    </div>
  </div>
<%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-primary" %>
<%= link_to 'Back', invoices_path, class: "btn btn-success" %>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-left">
  <li><%= link_to 'Products', products_path %></li>
  <li><%= link_to 'Invoices', invoices_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">   
    <% if user_signed_in? %>   
    <li><%= link_to current_user.email, edit_user_registration_path %></li>   
    <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>   
    <% else %>   
    <li><%= link_to "Sign In", user_session_path %></li>   
    <li><%= link_to "Register", new_user_registration_path %></li>   
    <% end %>   
 </ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Point of Sale App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Point of Sale App" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> <%= @product.name %></h3>
    </div>
    <div class="panel-body">
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name, required: true,input_html: { required: true } %>
        <%= f.input :price, required: true, input_html: { required: true } %>
        <%= f.association :tags, as: :select, multiple: true, required: true, input_html: { class: 'select-multiple', required: true } %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_search_form.html.erb
<div class="slight-top-margin">
  <%= form_tag(products_path, method: :get) do %>
    <%= text_field_tag :search_query, params[:search_query], :size => 20, :placeholder => "Comma seperated tags.. Eg: Tea,Beverage", :autocomplete => "off", :class => "form-control"%>
    <%= submit_tag "Search", class: "btn btn-primary btn-sm"%>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render "search_form" %>
<div class="slight-top-margin panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"> Products</h3>
  </div>
  <div class="panel-body">
    <table class='table table-hover table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= (!product.tags.blank? && (!product.tags.pluck(:name).blank?)) ? product.tags.pluck(:name) :  "No Tag Present"%></td>
            <td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= paginate @products %>
<%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', user: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="slight-top-margin col-md-8 offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> Product Name: <%= @product.name %></h3>
    </div>
    <div class="panel-body">
      <p><b>Product Price:</b>  <%= @product.price %></p>
      <p><b>Tags: </b> <%= (!@product.tags.blank? && (!@product.tags.pluck(:name).blank?)) ? @product.tags.pluck(:name) :  "No Tag Present"%></p>
    </div>
  <!-- <h4> Product Name: <%#= @product.name %> </h4> -->

</div>